### PR TITLE
Tour search

### PR DESCRIPTION
**Pull request by ShawnKagwa**
This is a new PR. I have done some code clean up on this as you had advised. I have run into multiple issues working with git rebase and everything might not be as you expect it to be.

1.  I have deleted all code that was not related to my work.
2. Added new code for conditional rendering of a button widget.
The text search feature allows for textual data to be searched on tours. 
A user enters a search term in the text field and taps on the search button, the search  term is passed onto the search_results constructor 

that fetches the data from the API when it is initialized. Any objects that are returned by the http call are listed in a list view. Tapping a single item on the list view opens it in the ViewObject screen.
The http data fetch functions are not fully implemented.
ric_1
ric_4
ric_2

### CODE REVIEW

**Comment by nguyendviet** [comment]
@ShawnKagwa Thank you. Your search bar seems to work. However, there are things you need to do before we can merge this. Please reach out if you need help.
- [ ] Create a search page or a drop down search bar, not replacing the whole Tour List page. You can see an example [here](https://github.com/umgc/spring2023/blob/team_a_dev/virotour/lib/src/tour/tour_edit_view.dart).
- [ ] You don't need to open a file or folder. You can hard code a list of objects as a mock API call and display them on your search result page or modal
- [ ] Resolve the conflicts. You can Google or use ChatGPT for this. Basically, while you're on your own branch, run ```git rebase team_a_dev`, resolve any conflict, push it to your remote branch.

**Comment by nguyendviet** [comment]
Duplicate of https://github.com/umgc/spring2023/pull/60

**Comment by ShawnKagwa** [comment]
I am totally not in a position to perform the rebase, very many things are breaking. I have no idea what I am doing. I need assistance on that.

**Comment by nguyendviet** [comment]
@ShawnKagwa Hey. No worries. Since we didn't hear from you. We've implemented this feature in https://github.com/umgc/spring2023/pull/60. I've taken you off ticket https://github.com/umgc/spring2023/issues/12. Please contact @khoaddnguyen to help with the docs for milestone 3.

**Pull request closed without merging**
