### PR TITLE
wheel_menu on all views 

### PR DESCRIPTION
**Pull request by SamsonAlemneh**

### CODE REVIEW

**Comment by SamsonAlemneh** [comment]
I had to use a previous clone to test the code for wheel_menu because of flask server issue. 
You may see older commits, but please focus on the recent one, Mar 10, 2023 wheel_menu_with_buttons, it contains all the new changes. 

Per Viet’s suggestion I used the settings page to add buttons for “Glow effect” and “VRView” still keeping the system theme dropdown. 

The code for wheel_menu is under the “seetings_view.dart” lines 23 – 67
On other views, only the action widget has been added to the appbar to display the wheel icon and add action to it. 
I have added one page, “empty_page_glow_vr.dart” to display a text when button is selected.   

-------





https://user-images.githubusercontent.com/66099861/224443042-bdf607b1-2179-43ed-b6c3-32c3af9a3dcd.mp4






Option 2

I also have the other option for the wheel_menu,  with a menu for the "Glow effect and VR view". I can also push that if needed. 



https://user-images.githubusercontent.com/66099861/224443089-053be3a4-ddc9-426d-96d5-e7c68a0dd406.mp4

**Comment by nguyendviet** [comment]
@SamsonAlemneh Thank you! Your wheel menu works. 
Please:
- [ ] Resolve conflict
- [ ] Resolve layout issue. This happens on both iOS and Android. I suggest you pick a smaller screen size and set the padding from there. You can look at [how I handled it](https://github.com/umgc/spring2023/blob/team_a_dev/virotour/lib/src/tour/tour_details_view.dart#L18-L23).
Screenshot 2023-03-11 at 21 08 55
Screenshot 2023-03-11 at 21 09 20
Screenshot 2023-03-11 at 21 13 14
Screenshot 2023-03-11 at 21 13 47

- [ ] Merge your PR

Note that this is a part of your ticket https://github.com/umgc/spring2023/issues/17 so it's not done yet. We'll need to continue with https://github.com/umgc/spring2023/issues/13 and https://github.com/umgc/spring2023/issues/18

**Comment by SamsonAlemneh** [comment]
@nguyendviet @tpbnick  I have added some changes to the branch per the comments for your review.

**Comment by SamsonAlemneh** [comment]
I 'll create another PR for glow effect and wheel menu

**Comment by nguyendviet** [comment]
@SamsonAlemneh It's almost there. Thank you for your work! Please check the tasks I've updated above.

**Comment by SamsonAlemneh** [comment]
I have adjusted the sizes of the the buttons on settings screen. I moved the back arrow on this screen to the right hand side to leave space for the hamburger menu. 

settings_view.dart - line 26 to end

buttons

**Comment by nguyendviet** [comment]
Duplicate of https://github.com/umgc/spring2023/pull/75

**Pull request closed without merging**
