### PR TITLE
Java 11 + Android Studio + Dart + Flutter: Set-up Demo App

### PR DESCRIPTION
**Pull request by tchangalov**
This PR includes screenshots for installing and setting up Dart & Flutter on Java 11 and Android Studio

### CODE REVIEW

**Review by nguyendviet — APPROVED** [review]
Thank you! This is helpful.

**Comment by nguyendviet** [comment]
@tchangalov Let's merge commit [adabf41](https://github.com/umgc/spring2023/pull/5/commits/adabf41db1651a74a83595b1e456b5d4e9636335) first. Then you can create another PR for the changes you've made to the prototype to avoid conflicts between different original branches.

**Comment by tchangalov** [comment]
Sure, let me create it.

**Comment by tchangalov** [comment]
@nguyendviet The pull request with commits only until adabf41d are pushed to a new branch, and the associated PR is located here: https://github.com/umgc/spring2023/pull/7/commits

Once it has enough approvals, we can merge it to "development", which I think should be our base branch.

**Comment by nguyendviet** [comment]
The `development` branch requires Rob's approval. If you want to merge 2 teams' branches together. Let's do it in a joint branch instead of merging directly to `team_a_dev`. Let me create that branch.

You're still welcome to merge team B to team A branch. Just keep each PR small so we can review them.

**Pull request closed without merging**
