### PR TITLE
wheel_menu added on other views

### PR DESCRIPTION
**Pull request by SamsonAlemneh**
I added the code in three files to show the wheel_menu on the appbar. However, the options that the wheel_menu provides (glow effect and VR view) are only relevant for the tour_detail_view. I believe. 

The Wheel Menu code is located in - 
tour_list_view – lines 71  - 117 and 222-232
tour_edit_view – lines 44  - 90 and 240-251
tour_detail_view – lines 27  - 73 and 91-102

------
For the app launch icon to work, we need to replace folders in two places 

•	android – we go to the following location /[virotour](https://github.com/umgc/spring2023/tree/wheel_menu_mar_2/virotour)/[android](https://github.com/umgc/spring2023/tree/wheel_menu_mar_2/virotour/android)/[app](https://github.com/umgc/spring2023/tree/wheel_menu_mar_2/virotour/android/app)/[src](https://github.com/umgc/spring2023/tree/wheel_menu_mar_2/virotour/android/app/src)/[main](https://github.com/umgc/spring2023/tree/wheel_menu_mar_2/virotour/android/app/src/main)/res/
and replace all five folders that start with “mipmap- …” with the new mipmap folders. 

•	iOS – we need to go to the following location [virotour](https://github.com/umgc/spring2023/tree/wheel_menu_mar_2/virotour)/[ios](https://github.com/umgc/spring2023/tree/wheel_menu_mar_2/virotour/ios)/[Runner](https://github.com/umgc/spring2023/tree/wheel_menu_mar_2/virotour/ios/Runner)/Assets.xcassets/ and replaced the folder AppIcon.appiconset  with the new AppIcon.appiconset  folder

menu on tour detail 1

menu on tour detail

### CODE REVIEW

**Comment by nguyendviet** [comment]
@SamsonAlemneh Did you test your code with this change? It looks like it brakes the build. Can you please:
- [ ] Verify that the app works
- [ ] Create a class for your Wheel Menu instead of pasting the same code to different files
Please let the team know if you need help.

**Comment by SamsonAlemneh** [comment]
Hi Viet

I should have mentioned this yesterday, I barely changed the initial code I pushed than duplicating it across the views. To describe what I did, I tested the changes in my existing environment, it worked fine, and I took screenshots that I attached showing the wheel_menu in tour_details_view.
When I was done, I thought the right way to do it was to clone team_a_dev again, apply the changes and push. The problem happened here, when I tried to run the app after cloning, I got this “XMLHttpRequest error”, even before I added the wheel_menu code. The only thing I did as I remember was “Get dependencies” after opening the app. I thought something happened to my environment and since I have already tested the changes, I added the wheel_menu codes to the different views and pushed it. 
After I saw your message this morning, I cloned team team_a_dev again to a separate folder and tried running it without wheel_menu code, I got the same error message.
Please look into it, I don’t think this has to do with the wheel_menu code because I made no significant changes. 

I need help with this and also please I need your help with creating the class for the wheel_menu code, I don’t want to hold us back because of this.

Thank you,

This is the error I kept getting 
image

**Comment by nguyendviet** [comment]
Hi @SamsonAlemneh 
That error means the Flask server is not turned on. You can follow the instruction in the `virotour_local` to start it.

Can you check with another team member who uses Windows to see if your code works on their machine? With the working code, your code does not compile on mine. Your old branch (mar_2 I think) worked well.

I suggest you move the buttons to the Settings page instead of the drop down from the existing wheel menu. Right now, there's a dedicated page when you click on the wheel menu icon.

**Comment by SamsonAlemneh** [comment]
I created a PR using on previous clone  https://github.com/umgc/spring2023/pull/46 addressing the comments given.
I wasn't successful with the flask server, I am still working on it.

**Comment by nguyendviet** [comment]
Duplicate of https://github.com/umgc/spring2023/pull/46

**Pull request closed without merging**
