### PR TITLE
Hamburger menu

### PR DESCRIPTION
**Pull request by menchukf**
Hamburger menu should be working for all the pages present currently.

### CODE REVIEW

**Comment by tpbnick** [comment]
It is working as expected on my machine:
image
Just my one question and removing any testing related code, and I will approve.

My code with the list tours and edit tour need to be merged into `team_a_dev` so we can link up the `Navigator` routes to the correct widget pages.

**Review by nguyendviet — DISMISSED** [review]
Good work! Note that the ticket for the hamburger menu isn't done yet.

**Comment by nguyendviet** [comment]
- [x] Resolve conflict. @menchukf This is not because of your code but because of the Flask server issues. I updated the List View so it won't get stuck in loading stage.
- [x] Add search option. Please refer to the requirements https://github.com/umgc/spring2023/issues/16 to change the options in your menu. I recommend:
  - [x] World icon change to Search tour not Create tour
  - [x] Plus icon change to Create tour not View tour
  - [x] Remove Publish tour

**Comment by tpbnick** [comment]
@nguyendviet Changes have been made, please give it a re-review.

**Review by nguyendviet — APPROVED** [review]
Thank you @tpbnick !

**Pull request merged**
